# Generated by Django 4.2.1 on 2023-09-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datas',
            name='Address',
        ),
        migrations.AlterField(
            model_name='datas',
            name='Name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
